AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - hello-1.0-SNAPSHOT
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
    - '*/*'
Resources:
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      CodeUri: s3://telenet-ent-cbe-deployments/028cf24b594bf5c938bdc33f5b5d283f
      MemorySize: 3008
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 5
      Events:
        HelloResource:
          Type: Api
          Properties:
            Path: /hello
            Method: POST
        WorldResource:
          Type: Api
          Properties:
            Path: /world
            Method: POST
