  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - hello-1.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    Hello:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: target/function.zip
        MemorySize: 3008
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 5
        Events:
          HelloResource:
            Type: Api
            Properties:
              Path: /hello
              Method: POST

          WorldResource:
            Type: Api
            Properties:
              Path: /world
              Method: POST
